// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/63c0b70385d718560e52d1e7
###
GET http://localhost:3000/contacts/63c0b70385d718560e52d1e8
###
GET http://localhost:3000/contacts/63c0b70385d718560e52d1e9

##### Create a new user 

POST http://localhost:3000/contacts/ HTTP/1.1 
content-type: application/json

{
"firstName":"Ashley", 
"lastName":"Weaver", 
"email":"aWeaver@test.com", 
"favoriteColor":"Brown",
 "birthday":"06/19/2000"
}
### DISPLAY CONTACTS LIST
GET http://localhost:3000/contacts
###Update a contact 
PUT http://localhost:3000/contacts/63caab064c1d7b3066fdb5ed HTTP/1.1
content-type: application/json

{
    "firstName":"rodolfo2", 
    "lastName":"mar", 
    "email":"prueba@test.com", 
    "favoriteColor":"green",
    "birthday":"06/19/2003"
}


