// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/63c0b70385d718560e52d1e7
###
GET http://localhost:3000/contacts/63c0b70385d718560e52d1e8
###
GET http://localhost:3000/contacts/63c0b70385d718560e52d1e9

// PRODUCTION Deploy
###
GET https://cse341-instructor.herokuapp.com/contacts
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4
